server:
  port: 8888
#text: 开发  dev
#text: 测试  //三个留一个 test
#text: 生产  prod

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles:
    #当前为开发环境
    active: dev


 #日志配置
logging:
  level:
    root: INFO # 根日志级别
    com.ymsd: DEBUG # 指定包的日志级别
  file:
    name: myapplication.log # 日志文件名
    path: /var/log/myapplication/ # 日志文件路径
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 文件日志输出格式
  max-history: 7 # 最大保留日志文件数量


